title: PureInsight
email: jahanzebliaqatkhan@hotmail.com
description: >-
  Stay updated with the latest trend is our motto. We try our best to keep you up-to-date with innovation in tech.

default_cover: 
  link: /assets/images/default_cover.png
  alt: This is a placeholder image because a cover for the post is not available

default_author:
  image: default.png
  
collections:
  authors:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
